name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.1

      - name: Install dependencies
        run: python -m pip install pytest

      - name: Run tests
        run: pytest